name: Auto-merge Dependabot
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
permissions:
  pull-requests: write
  contents: write
jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
