# GitHub Pages deployment for the generated Maven site.
# This workflow runs only when triggered manually. To ship sites on release tags,
# replace the `on:` block with the commented configuration below.
#
# on:
#   push:
#     tags:
#       - 'v*'

name: Publish Maven Site (manual)

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Optional tag to annotate the publication'
        required: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Build Maven site
        run: mvn -q clean site

      - name: Stage site artefact
        run: |
          mkdir -p site
          cp -R target/site/. site/

      - name: Upload site artefact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    runs-on: ubuntu-latest
    needs: build-site
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          build_version: ${{ github.event.inputs.release_tag || github.run_number }}
