name: Static Analysis

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  pull-requests: read

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Verify with SpotBugs and Dependency-Check
        run: mvn -B -ntp verify

      - name: SonarCloud scan
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORG: ${{ secrets.SONAR_ORG }}
        run: >-
          mvn -B -ntp sonar:sonar
          -Dsonar.login=${SONAR_TOKEN}
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=${SONAR_ORG}
          -Dsonar.projectKey=${SONAR_PROJECT_KEY}
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
